#!/usr/bin/env bash

# black cursor
update-alternatives \
    --set x-cursor-theme \
          /usr/share/icons/DMZ-Black/cursor.theme


# plymouth theme
update-alternatives \
    --install /lib/plymouth/themes/default.plymouth \
              default.plymouth \
              /lib/plymouth/themes/blubuntu-logo/ubuntu-logo.plymouth \
              42 \
    --slave   /lib/plymouth/themes/default.grub \
              default.plymouth.grub \
              /lib/plymouth/themes/blubuntu-logo/ubuntu-logo.grub
update-alternatives \
    --set default.plymouth \
          /lib/plymouth/themes/blubuntu-logo/ubuntu-logo.plymouth

update-alternatives \
    --install /lib/plymouth/themes/text.plymouth \
              text.plymouth \
              /lib/plymouth/themes/blubuntu-text/ubuntu-text.plymouth \
              42
update-alternatives \
    --set text.plymouth \
          /lib/plymouth/themes/blubuntu-text/ubuntu-text.plymouth

update-grub


# gnome default background
path=/usr/share/backgrounds
name=Starry_Night_Over_the_Rhone_by_Vincent_van_Gogh.jpg

file=/usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema.override
sed -i "s|^\(picture-uri='file://$path\).\+\('\)\$|\1/$name\2|" $file
glib-compile-schemas /usr/share/glib-2.0/schemas


# lightdm default background
xhost +SI:localuser:lightdm
chown lightdm:lightdm /run/user/1000
chown -R lightdm:lightdm /run/user/1000/dconf

greeter=com.canonical.unity-greeter
su lightdm -c "gsettings set $greeter background '$path/$name'"
su lightdm -c "gsettings set $greeter background-color '#000014'"

chown root:root /run/user/1000
